{% set version = "1.1.1" %}

package:
  name: micro_sam
  version: {{ version }}

source:
  url: https://github.com/computational-cell-analytics/micro-sam/archive/v{{ version }}.tar.gz
  sha256: 0212cee6fe8a6339572e9dddaf09caf23fc82e9e08c5f96062867b3465c98255

build:
  entry_points:
    - micro_sam.annotator_2d = micro_sam.sam_annotator.annotator_2d:main
    - micro_sam.annotator_3d = micro_sam.sam_annotator.annotator_3d:main
    - micro_sam.annotator_tracking = micro_sam.sam_annotator.annotator_tracking:main
    - micro_sam.automatic_segmentation = micro_sam.automatic_segmentation:main
    - micro_sam.benchmark_sam = micro_sam.evaluation.benchmark_datasets:main
    - micro_sam.image_series_annotator = micro_sam.sam_annotator.image_series_annotator:main
    - micro_sam.precompute_embeddings = micro_sam.precompute_state:main
  noarch: python
  number: 1
  script: pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - kornia
    - napari >=0.5
    - nifty =1.2.1
    - pooch
    - pyqt
    - python >={{ python_min }}
    - python-elf >=0.4.8
    - python-xxhash
    - pytorch >=2.4.0
    - segment-anything
    - torchvision
    - torch_em >=0.7.1
    - tqdm
    - timm
    - zarr
    - __unix              # [linux]
    # We don't really have a pytorch package at conda-forge
    # Users are forced to find a workaround.
    # This nifty pin helps them automatically find a workaround...
    # https://github.com/conda-forge/micro_sam-feedstock/issues/24
    # However to build on conda-forge's architecture,
    # we use OSX to build a package with a stricter pinning
    # against nifty
    # The unix package, specific to unix, has a less strict pin on nifty
    - nifty =1.2.1=*_4   # [osx]
    - protobuf <5        # [osx]

test:
  imports:
    - micro_sam
  source_files:
    - test/**/*.py
  commands:
    - python -m unittest discover -s test -v

about:
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Segment Anything for Microscopy.
  home: https://github.com/computational-cell-analytics/micro-sam

extra:
  recipe-maintainers:
    - constantinpape
